name: siblenv
channels:
  - defaults
dependencies:
  - python=3.8
  - black
  - dash
  - flake8
  - ipykernel
  - matplotlib
  - pandas
  - pillow
  - pytest
  - pytest-cov
  - seaborn
  - scikit-image
  - scipy
  - xlrd
