{% set version = "0.0.3" %}

package:
  name: xyfigure
  version: {{ version }}

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/sandialabs/sibl
  license: MIT
  summary: 'A library for xy plotting and processing'
  description: |
    This module plots series x versus y data, and 
    can signal process the y data.
  dev_url: https://github.com/sandialabs/sibl
  doc_url: https://github.com/sandialabs/sibl/blob/master/xyfigure
  doc_source_url: https://github.com/sandialabs/sibl/blob/master/xyfigure/documentation.md
  